apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: hello-kubernetes
        image: carvicsforth/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: {{ .Values.message | quote }}
        - name: HANDLER_PATH_PREFIX
          value: {{ .Values.endpoint | quote }}
        - name: RENDER_PATH_PREFIX
          value: {{ .Values.endpoint | quote }}
        resources:
          limits:
            {{- if .Values.cpuLimit }}
            cpu: {{ .Values.cpuLimit | quote }}
            {{- end }}